[2024-01-30T23:21:30.013+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: meteo.python_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-30T23:21:30.065+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: meteo.python_task scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-01-30T23:21:30.066+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-30T23:21:30.342+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): python_task> on 2024-01-01 00:00:00+00:00
[2024-01-30T23:21:30.450+0100] {standard_task_runner.py:60} INFO - Started process 7760 to run task
[2024-01-30T23:21:30.461+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'meteo', 'python_task', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/meteo.py', '--cfg-path', '/tmp/tmpr2d9pvwq']
[2024-01-30T23:21:30.476+0100] {standard_task_runner.py:88} INFO - Job 19: Subtask python_task
[2024-01-30T23:21:30.766+0100] {task_command.py:423} INFO - Running <TaskInstance: meteo.python_task scheduled__2024-01-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-30T23:21:31.380+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='meteo' AIRFLOW_CTX_TASK_ID='python_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-01-30T23:21:32.422+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-30T23:21:32.448+0100] {client.py:496} INFO - Writing to '/user/Datalake/raw/temperature/2024-01-30.json'.
[2024-01-30T23:21:49.851+0100] {logging_mixin.py:188} INFO - Les données ont été sauvegardées dans /user/Datalake/raw/temperature/2024-01-30.json
[2024-01-30T23:21:50.338+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-30T23:21:50.339+0100] {client.py:496} INFO - Writing to '/user/Datalake/raw/tempreeltime/2024-01-30/23_21_31.json'.
[2024-01-30T23:21:51.387+0100] {logging_mixin.py:188} INFO - Les données ont été sauvegardées dans /user/Datalake/raw/tempreeltime/2024-01-30/23_21_31.json
[2024-01-30T23:21:51.410+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T23:21:51.444+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=meteo, task_id=python_task, execution_date=20240101T000000, start_date=20240130T222130, end_date=20240130T222151
[2024-01-30T23:21:52.046+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T23:21:52.086+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
